import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Victor Buarque Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-w-screen bg-gradient-to-b from-sky-600 to-sky-300">
          <Header />
        </div>
        <section className="min-h-full flex flex-1 items-center justify-center py-32">{children}</section>
      </body>
    </html>
  );
}
